"""Compatibility bridge for the migrated regularized zoning implementation."""

from roadnet_partition.zoning.regularized._legacy_monolith import (
    EPS,
    MacroCandidate,
    ObjectiveParams,
    SearchContext,
    SearchParams,
    SearchSetting,
    append_rows,
    apply_merge,
    apply_split,
    assert_exact_target_clusters,
    assert_partition_valid,
    baseline_for_algorithm,
    best_merge_only_candidate,
    best_merge_split_candidate,
    best_split_only_candidate,
    build_cluster_demand,
    build_cluster_nodes,
    build_context,
    build_macro_candidate,
    build_settings,
    candidate_merge_targets,
    capacity_component,
    capacity_penalty_for_value,
    clean_setting_value,
    cluster_adjacency,
    edge_value,
    greedy_merge_once_to_reduce_k,
    legacy_setting_id,
    load_config,
    load_demand,
    load_graph,
    load_partition,
    move_delta,
    normalize_partition_to_target,
    objective_components,
    project_path,
    ranked_merge_sources,
    ranked_split_sources,
    regularized_algorithm_name,
    relabel_partition,
    require_keys,
    run_from_config,
    run_search,
    save_partition,
    setting_id,
    source_remains_connected,
    split_assignment,
    split_seed_pair,
    target_cluster_count,
    target_demand,
    validate_config,
    write_run_config,
)

__all__ = [name for name in globals() if not name.startswith("_")]
