"""Compatibility bridge for the migrated Supply implementation."""

from roadnet_partition.downstream.supply import (
    CARPOOL_MERGE_GAP_S,
    DEMAND_DIR,
    DEMAND_TABLE,
    DRIVER_BLOCKS,
    FLEET_COLUMNS,
    IN_SERVICE_COLUMNS,
    LOGGER,
    MAX_GAP_MINUTES,
    MERGE_WITH_DEMAND,
    ORDERS_PATH,
    ORDER_USE_COLUMNS,
    OUTPUT_DIR,
    SLOT_DURATION_MIN,
    TAU_IDLE_MINUTES,
    TRIP_SEGMENT_COLUMNS,
    _cluster_positions,
    _dense_cluster_array_to_frame,
    _expand_interval_slots,
    _fleet_arrays_to_frame,
    _inservice_array_to_frame,
    _slot_positions,
    attach_global_fleet_to_all_clusters,
    build_cluster_universe,
    build_exclusive_trip_segments,
    build_global_cluster_index,
    build_global_slot_index,
    build_trip_segments,
    complete_slot_cluster_grid,
    compute_available_by_cluster,
    compute_fleet_lower_bound,
    compute_in_service_od,
    compute_supply_variables,
    configure_file_logging,
    driver_block_id,
    extract_idle_windows,
    filter_valid_orders,
    generate_slots,
    load_orders,
    merge_supply_with_demand,
    process_orders_frame,
    reconstruct_driver_chains,
    resolve_carpool_trip_groups,
    run_chunked_pipeline,
    run_pipeline,
    save_csv_gz,
    serialize_list_columns,
    write_json,
)

__all__ = [name for name in globals() if not name.startswith("_")]
