name: bj_road_partition
channels:
  - conda-forge
dependencies:
  - python=3.11
  - osmnx
  - geopandas
  - shapely
  - pyproj
  - networkx
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - scipy
  - python-igraph
  - leidenalg
  - pyyaml
  - tqdm
  - pyogrio
  - rtree
  - fiona
  - pip
  - pip:
      - python-louvain
